source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Using mysql database for active record
gem 'mysql2', '~> 0.3.20'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-script-source', '1.8.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Rack-attack middleware for throttles and restrictions
gem 'rack-attack'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# use nokogiri for parsing html
gem 'nokogiri'
# use rest-client for rest actions
gem 'rest-client'
# use sidekiq for background tasks
gem 'sidekiq'
# use sidekiq scheduler for scheduling background tasks
gem 'sidekiq-scheduler', '~> 2.0'

# Use redcarpet for rendering markdown in the help center
gem 'redcarpet'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use will_paginate for pagination
gem 'will_paginate'

# For contact forms
gem 'mail_form'
gem 'simple_form'

# use cancancan for authorization
gem 'cancancan', '~> 1.10'

# TODO: Use Passenger as the app server
# gem 'passenger'

# using devise for authentication
gem 'devise'
# using devise_invitable for inviting users to the platform for the beta
# may also be used later for users to invite their friends
gem 'devise_invitable'

# use mailcatcher for development
gem 'mailcatcher'

# allow for composite primary keys in rails
gem 'composite_primary_keys', '~> 8.1'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Faker for generating fake data
gem 'faker'

group :development do

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  group :test do
    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
    gem 'byebug'

    # rspec testing framework
    gem 'rspec-rails'

    # Factory girl for testing
    gem 'factory_girl_rails', '~> 4.0'
  end
  
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
